"""criação da tabela jogador

Revision ID: 219a3b7bf7f8
Revises: 54b750aa9516
Create Date: 2025-05-21 19:03:44.883338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219a3b7bf7f8'
down_revision = '54b750aa9516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jogador')
    # ### end Alembic commands ###
