"""Adiciona tabela jogador_insignia

Revision ID: 8f8b3220f15a
Revises: da467fdb9290
Create Date: 2025-06-20 12:29:59.187811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8b3220f15a'
down_revision = 'da467fdb9290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogador_insignia',
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('insignia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insignia_id'], ['insignia.id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogador.id'], ),
    sa.PrimaryKeyConstraint('jogador_id', 'insignia_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogador_insignia')
    # ### end Alembic commands ###
